#!/usr/bin/env python3
"""find_predecessors.py - the duplicate / novelty gate.

Read-only. Searches ALL canonical claims, disputes, decisions and observables -
including withdrawn, contradicted, superseded and negative-result records - for
the closest semantic predecessor of a candidate statement.

    find_predecessors.py "candidate statement ..." [--top 5] [--json]

WHY THIS EXISTS
In TASK-2026-08-10-AMP096 the lead labelled candidate C2 "the finding of the
task". C2 said the amplitude and the exponent were co-generated by an
extrapolation exponent p = 1/2 chosen by assuming nu = 2. METH-EXTRAP-001 -
status `withdrawn`, and therefore invisible to anyone who only reads live
claims - already said exactly that, with the same four-form chi2/dof table. The
red team caught it. Nothing else would have.

Dead claims are the ones most likely to be rediscovered, precisely because they
are not in anybody's working set. This tool searches them FIRST.

Scoring is deliberately crude - token overlap with weighting for rare terms and
for shared IDs. It is a RETRIEVAL AID, not a judgement: it surfaces candidates
for the lead to read. It cannot certify novelty and does not try. Charter 3
reserves that for the researcher.
"""
from __future__ import annotations

import argparse
import glob
import json
import math
import os
import re
import sys
from collections import Counter

try:
    import yaml
except ImportError:
    sys.exit("PyYAML required")

KINDS = ("claims", "disputes", "decisions", "observables")
# Fields worth matching on, per kind. Deliberately includes the fields where a
# superseded result leaves its trace: provenance_note, confidence_basis, notes.
TEXT_FIELDS = ("statement", "decision", "question", "rationale", "name",
               "definition", "provenance_note", "confidence_basis",
               "evidence_note", "caveat", "note", "notes", "retirement_note",
               "why_it_matters", "difference", "open_task", "summary",
               "description", "resolution_criteria")

STOP = set("""a an the of in on to for is are was were be been being and or but if
then than that this these those with without from by as at it its into over under
which who whom whose not no nor so such can may might must should would could
we our us you your they their he she his her i me my""".split())

ID_RE = re.compile(r"\b(?:CB|CASEA|VR|METH|INFRA|PPS|EV|OBS|SRC|DEC|DISP|EXP)"
                   r"(?:-[A-Z0-9]+)+\b")
# Terms that carry most of the discriminating signal in this project.
DOMAIN = set("""extrapolation exponent amplitude crossing window binder locator
parameterization nu phi zeta lambda circular assumed assuming postdiction
observable estimator bootstrap finite-size collapse jacobian prefactor
diffusive replica duality self-dual boundary""".split())


def tokens(text: str) -> Counter:
    text = text.lower()
    toks = re.findall(r"[a-z_][a-z0-9_.^-]{1,}", text)
    return Counter(t for t in toks if t not in STOP and len(t) > 2)


def harvest(doc, depth=0):
    """Concatenate the human-readable text of an entity."""
    out = []
    if depth > 4:
        return out
    if isinstance(doc, dict):
        for k, v in doc.items():
            if k in TEXT_FIELDS and isinstance(v, str):
                out.append(v)
            elif isinstance(v, (dict, list)):
                out.extend(harvest(v, depth + 1))
            elif isinstance(v, str) and k in ("verdict", "status"):
                out.append(v)
    elif isinstance(doc, list):
        for v in doc:
            out.extend(harvest(v, depth + 1))
    return out


def load(root):
    ents = []
    for kind in KINDS:
        for p in sorted(glob.glob(os.path.join(root, "research", "state", kind, "*.yaml"))):
            try:
                d = yaml.safe_load(open(p, encoding="utf-8")) or {}
            except Exception:
                continue
            if not isinstance(d, dict):
                continue
            text = " ".join(harvest(d))
            ents.append({
                "id": d.get("id") or os.path.basename(p)[:-5],
                "kind": kind,
                "path": os.path.relpath(p, root),
                "status": d.get("epistemic_status") or d.get("status") or "",
                "claim_kind": d.get("claim_kind") or "",
                "statement": (d.get("statement") or d.get("decision")
                              or d.get("question") or d.get("name") or "")[:300],
                "text": text,
                "tokens": tokens(text),
            })
    return ents


# A dead record is the MOST likely thing to be rediscovered, so it is boosted
# rather than filtered out.
DEAD = {"withdrawn", "contradicted", "superseded", "refuted", "retired",
        "deprecated", "killed"}


def score(cand_toks, cand_ids, ent, idf):
    shared = set(cand_toks) & set(ent["tokens"])
    if not shared:
        base = 0.0
    else:
        base = sum(idf.get(t, 1.0) * min(cand_toks[t], ent["tokens"][t]) for t in shared)
        base /= math.sqrt(sum(cand_toks.values()) * sum(ent["tokens"].values()) or 1)
    dom = len(shared & DOMAIN) * 0.05
    ids = len(cand_ids & set(ID_RE.findall(ent["text"]))) * 0.10
    dead = 0.15 if str(ent["status"]).lower() in DEAD else 0.0
    neg = 0.10 if ent.get("claim_kind") == "negative_result" else 0.0
    return base + dom + ids + dead + neg


def find(root, statement, top=5):
    ents = load(root)
    df = Counter()
    for e in ents:
        df.update(set(e["tokens"]))
    n = len(ents) or 1
    idf = {t: math.log(1 + n / (1 + c)) for t, c in df.items()}

    ct = tokens(statement)
    cids = set(ID_RE.findall(statement))
    ranked = sorted(ents, key=lambda e: score(ct, cids, e, idf), reverse=True)
    out = []
    for e in ranked[:top]:
        s = score(ct, cids, e, idf)
        out.append({"id": e["id"], "kind": e["kind"], "status": e["status"],
                    "score": round(s, 4), "statement": e["statement"],
                    "path": e["path"],
                    "dead_record": str(e["status"]).lower() in DEAD})
    return out


CLASSES = """
If an entity below already carries the candidate's epistemic content, the output
is NOT novelty. Classify it as one of:

  replication        same result, independently obtained
  corroboration      same conclusion, different evidence or method
  rediscovery        we already knew this and did not notice   <- the C2 failure
  provenance repair  the record was wrong about its own history

Record the closest predecessor for EVERY candidate in NOVELTY_GATE.md, including
those where the honest answer is "none found". Charter 3: an agent may not
declare a contribution novel because a search found nothing.
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("statement", nargs="+")
    ap.add_argument("--repo", default=os.path.join(os.path.dirname(__file__), "..", ".."))
    ap.add_argument("--top", type=int, default=5)
    ap.add_argument("--json", action="store_true")
    a = ap.parse_args()
    root = os.path.abspath(a.repo)
    stmt = " ".join(a.statement)

    hits = find(root, stmt, a.top)
    if a.json:
        print(json.dumps(hits, indent=2))
        return 0

    print(f"candidate: {stmt[:200]}\n")
    print(f"closest canonical predecessors (dead records boosted, not hidden):\n")
    for h in hits:
        flag = "  <-- DEAD RECORD" if h["dead_record"] else ""
        print(f"  {h['score']:6.3f}  {h['id']:24s} [{h['kind'][:-1]}, "
              f"{h['status'] or 'n/a'}]{flag}")
        print(f"          {h['statement'][:150]}")
        print(f"          {h['path']}")
    print(CLASSES)
    return 0


if __name__ == "__main__":
    sys.exit(main())
